modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/cixxytt/RubiesAndGems/issues" #optional
[[mods]] #mandatory
modId="rm" #mandatory
version="1.15.2-1.0.0" #mandatory
displayName="Rubies & Gems" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/cixxytt/RubiesAndGems" #optional
logoFile="examplemod.png" #optional
credits="" #optional
authors="cixxyt" #optional
description='''
A mod for adding new Tools, Armour, Weapons, Resources and more!
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
